// <auto-generated />
namespace ib_dotnet.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class topic_reply_relationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(topic_reply_relationship));
        
        string IMigrationMetadata.Id
        {
            get { return "201306111141537_topic_reply_relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
